Update sync2azure.yml

diff --git a/.github/workflows/sync2azure.yml b/.github/workflows/sync2azure.yml
--- a/.github/workflows/sync2azure.yml
+++ b/.github/workflows/sync2azure.yml
@@ -47,6 +47,11 @@ jobs:
           
       - name: Clone Azure DevOps Repository
         run: |
+          # Check if the PAT is set
+          if [ -z "$AZURE_DEVOPS_PAT" ]; then
+            echo "Error: AZURE_DEVOPS_PAT is not set"
+            exit 1
+          fi
           # Clone the Azure DevOps repo
           CLONE_URL="https://$AZURE_DEVOPS_ORG:${{ env.AZURE_DEVOPS_PAT }}@dev.azure.com/$AZURE_DEVOPS_ORG/$AZURE_DEVOPS_PROJECT/_git/$AZURE_REPO_NAME"
 
